pub mod cli;
pub mod commands;
pub mod discovery;
pub mod identity;
pub mod logging;
mod network;
pub mod network_hint;
pub mod platform;
pub mod remote;
pub mod service;
pub mod skill;
pub mod ssh_client;
pub mod state;
pub mod tailscale;
pub mod updater;
