use crate::state::{Machine, StatePaths};
use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

const SKILL_MD: &str = r#"---
name: fleet
description: Use the user's local fleet of named development machines over SSH.
---

# Fleet

Fleet connects the user's local development machines. The user chooses the target machine; do not schedule or redirect work yourself.

Read `references/machines.md` for current machine names. Access a requested member with ordinary SSH using its `<name>.local` address. Fleet does not own the task, repository, or agent session.

Preserve host-key verification. Never replace a `.local` hostname with a persisted IP address.
"#;

pub fn initialize(paths: &StatePaths) -> Result<()> {
    fs::create_dir_all(paths.skill_dir().join("references"))
        .context("create Fleet skill directory")?;
    crate::state::atomic_write(
        &paths.skill_dir().join("SKILL.md"),
        SKILL_MD.as_bytes(),
        0o644,
    )?;
    regenerate(paths)?;
    install_link(paths)
}

pub fn uninstall(paths: &StatePaths) -> Result<()> {
    uninstall_from(paths, &agents_root()?)
}

fn uninstall_from(paths: &StatePaths, agents: &std::path::Path) -> Result<()> {
    let link = agents.join("skills/fleet");
    if link.symlink_metadata().is_ok() {
        let target = fs::read_link(&link).ok();
        if target.as_deref() == Some(paths.skill_dir().as_path()) {
            fs::remove_file(&link).context("remove Fleet skill link")?;
        }
    }
    if paths.skill_dir().exists() {
        fs::remove_dir_all(paths.skill_dir()).context("remove Fleet skill")?;
    }
    Ok(())
}

pub fn save_member(paths: &StatePaths, machine: &Machine) -> Result<()> {
    fs::create_dir_all(paths.inventory_dir()).context("create inventory directory")?;
    let content = toml::to_string_pretty(machine).context("serialize member")?;
    crate::state::atomic_write(
        &paths.inventory_dir().join(format!("{}.toml", machine.id)),
        content.as_bytes(),
        0o600,
    )?;
    regenerate(paths)
}

pub fn remove_member(paths: &StatePaths, id: uuid::Uuid) -> Result<()> {
    let path = paths.inventory_dir().join(format!("{id}.toml"));
    if path.exists() {
        fs::remove_file(path).context("remove member inventory")?;
    }
    regenerate(paths)
}

pub fn load_members(paths: &StatePaths) -> Result<Vec<Machine>> {
    let mut members = Vec::new();
    if !paths.inventory_dir().exists() {
        return Ok(members);
    }
    for entry in fs::read_dir(paths.inventory_dir()).context("read inventory")? {
        let path = entry?.path();
        if path.extension().and_then(|value| value.to_str()) != Some("toml") {
            continue;
        }
        let content =
            fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
        members
            .push(toml::from_str(&content).with_context(|| format!("parse {}", path.display()))?);
    }
    members.sort_by(|left, right| left.name.cmp(&right.name));
    Ok(members)
}

pub fn regenerate(paths: &StatePaths) -> Result<()> {
    let Some(config) = paths.load()? else {
        return Ok(());
    };
    let members = load_members(paths)?;
    let mut output = String::from(
        "# Fleet machines\n\nGenerated by Fleet. The user chooses which machine should receive work.\n\n",
    );
    output.push_str("## Captain\n\n");
    output.push_str(&machine_line(&config.machine, true));
    output.push_str("\n## Members\n\n");
    if members.is_empty() {
        output.push_str("No members have joined yet.\n");
    } else {
        for member in members {
            output.push_str(&machine_line(&member, false));
        }
    }
    fs::create_dir_all(paths.skill_dir().join("references"))?;
    crate::state::atomic_write(
        &paths.skill_dir().join("references/machines.md"),
        output.as_bytes(),
        0o644,
    )
}

fn machine_line(machine: &Machine, is_local: bool) -> String {
    let tools = machine
        .tools
        .iter()
        .filter(|state| state.installed)
        .map(|state| state.tool.display_name())
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "- **{}**{} — `{}`; color {}; {} {}; SSH user `{}`; tools: {}\n",
        machine.name,
        if is_local { " (This machine)" } else { "" },
        machine.host(),
        machine.color,
        machine.os,
        machine.arch,
        machine.ssh_user,
        if tools.is_empty() {
            "none detected"
        } else {
            &tools
        },
    )
}

fn agents_root() -> Result<PathBuf> {
    if let Some(path) = std::env::var_os("FLEET_AGENTS_HOME") {
        return Ok(path.into());
    }
    Ok(dirs::home_dir()
        .context("could not determine home directory")?
        .join(".agents"))
}

fn install_link(paths: &StatePaths) -> Result<()> {
    let skills = agents_root()?.join("skills");
    fs::create_dir_all(&skills).context("create agent skills directory")?;
    let link = skills.join("fleet");
    if link.exists() || link.symlink_metadata().is_ok() {
        let target = fs::read_link(&link).ok();
        if target.as_deref() == Some(paths.skill_dir().as_path()) {
            return Ok(());
        }
        anyhow::bail!(
            "{} already exists and is not Fleet's skill link",
            link.display()
        );
    }
    #[cfg(unix)]
    std::os::unix::fs::symlink(paths.skill_dir(), &link)
        .with_context(|| format!("link Fleet skill at {}", link.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::Color;
    use crate::state::{LocalConfig, Role, STATE_VERSION, ToolState};
    use uuid::Uuid;

    fn machine(name: &str) -> Machine {
        Machine {
            id: Uuid::new_v4(),
            name: name.into(),
            color: Color::Emerald,
            ssh_user: "dev".into(),
            os: "linux".into(),
            arch: "x86_64".into(),
            tools: vec![ToolState {
                tool: crate::cli::Tool::Codex,
                installed: true,
            }],
            public_identity: "ssh-ed25519 AAAA".into(),
            ssh_host_key: None,
        }
    }

    #[test]
    fn generated_inventory_lists_captain_and_members() {
        let temp = tempfile::tempdir().unwrap();
        let paths = StatePaths {
            root: temp.path().join(".fleet"),
        };
        paths
            .save(&LocalConfig {
                version: STATE_VERSION,
                role: Role::Captain,
                machine: machine("obsidian"),
                captain: None,
            })
            .unwrap();
        save_member(&paths, &machine("emerald")).unwrap();
        let output = fs::read_to_string(paths.skill_dir().join("references/machines.md")).unwrap();
        assert!(output.contains("**obsidian** (This machine) — `obsidian.local`"));
        assert!(output.contains("**emerald** — `emerald.local`"));
        assert_eq!(output.matches("This machine").count(), 1);
    }

    #[test]
    fn uninstall_removes_only_fleets_own_skill_link() {
        let temp = tempfile::tempdir().unwrap();
        let paths = StatePaths {
            root: temp.path().join(".fleet"),
        };
        let agents = temp.path().join(".agents");
        fs::create_dir_all(paths.skill_dir()).unwrap();
        fs::create_dir_all(agents.join("skills")).unwrap();
        std::os::unix::fs::symlink(paths.skill_dir(), agents.join("skills/fleet")).unwrap();
        uninstall_from(&paths, &agents).unwrap();
        assert!(agents.join("skills").exists());
        assert!(!agents.join("skills/fleet").exists());
        assert!(!paths.skill_dir().exists());
    }
}
