use crate::cli::TransportRoute;
use crate::skill;
use crate::state::{StatePaths, atomic_write};
use anyhow::{Context, Result};
use std::fs;
use std::io;
use std::net::{Shutdown, TcpStream};
use std::path::Path;
use uuid::Uuid;

pub fn initialize(paths: &StatePaths) -> Result<()> {
    let home = dirs::home_dir().context("could not determine home directory")?;
    let ssh = home.join(".ssh");
    fs::create_dir_all(&ssh).context("create captain .ssh directory")?;
    set_mode(&ssh, 0o700)?;
    let config = ssh.join("config");
    let include = format!("Include {}", quote_path(&paths.root.join("ssh_config")));
    let existing = fs::read_to_string(&config).unwrap_or_default();
    if !existing.lines().any(|line| line.trim() == include) {
        let next = with_fleet_include(&existing, &include);
        atomic_write(&config, next.as_bytes(), 0o600)?;
    }
    regenerate(paths)
}

fn with_fleet_include(existing: &str, include: &str) -> String {
    let mut next = format!("# Fleet member configuration\n{include}\n");
    if !existing.is_empty() {
        next.push('\n');
        next.push_str(existing);
        if !next.ends_with('\n') {
            next.push('\n');
        }
    }
    next
}

pub fn uninstall(paths: &StatePaths) -> Result<()> {
    let home = dirs::home_dir().context("could not determine home directory")?;
    let config = home.join(".ssh/config");
    if config.exists() {
        let include = format!("Include {}", quote_path(&paths.root.join("ssh_config")));
        let existing = fs::read_to_string(&config).context("read SSH client config")?;
        if let Some(next) = without_fleet_include(&existing, &include) {
            atomic_write(&config, next.as_bytes(), 0o600)?;
        }
    }
    for managed in [paths.root.join("ssh_config"), paths.known_hosts()] {
        if managed.exists() {
            fs::remove_file(&managed).with_context(|| format!("remove {}", managed.display()))?;
        }
    }
    Ok(())
}

fn without_fleet_include(existing: &str, include: &str) -> Option<String> {
    let mut retained = Vec::new();
    let mut removed = false;
    for line in existing.lines() {
        if line.trim() == include {
            if retained
                .last()
                .is_some_and(|previous: &&str| previous.trim() == "# Fleet member configuration")
            {
                retained.pop();
            }
            removed = true;
            continue;
        }
        retained.push(line);
    }
    removed.then(|| {
        let mut next = retained.join("\n");
        if !next.is_empty() {
            next.push('\n');
        }
        next
    })
}

pub fn regenerate(paths: &StatePaths) -> Result<()> {
    let executable = std::env::current_exe().context("locate the Fleet executable")?;
    regenerate_with_executable(paths, &executable)
}

fn regenerate_with_executable(paths: &StatePaths, executable: &Path) -> Result<()> {
    let executable = safe_proxy_executable(executable)?;
    let mut output = String::from("# Generated by Fleet. Do not edit.\n");
    let mut known_hosts = String::from("# Generated by Fleet. Do not edit.\n");
    for member in skill::load_members(paths)? {
        output.push_str(&format!(
            "\nHost {}\n  User {}\n  Port 22\n  IdentityFile {}\n  IdentitiesOnly yes\n  UserKnownHostsFile {}\n  StrictHostKeyChecking yes\n  UpdateHostKeys no\n  ProxyCommand {} transport connect --member {}\n",
            member.host(),
            member.ssh_user,
            quote_path(&paths.identity_dir().join("id_ed25519")),
            quote_path(&paths.known_hosts()),
            executable,
            member.id,
        ));
        if let Some(host_key) = &member.ssh_host_key {
            let mut fields = host_key.split_whitespace();
            if let (Some(algorithm), Some(encoded)) = (fields.next(), fields.next()) {
                known_hosts.push_str(&format!("{} {} {}\n", member.host(), algorithm, encoded));
            }
        }
    }
    atomic_write(&paths.root.join("ssh_config"), output.as_bytes(), 0o600)?;
    atomic_write(&paths.known_hosts(), known_hosts.as_bytes(), 0o600)
}

/// Implements the byte-stream side of Fleet's OpenSSH ProxyCommand.
///
/// The UUID is resolved only through the protected captain inventory. The
/// initial seam deliberately retains native `.local` routing; a Tailscale
/// endpoint selector can be added here without changing generated SSH config.
pub fn transport_connect(paths: &StatePaths, member_id: Uuid, route: TransportRoute) -> Result<()> {
    let member = skill::load_members(paths)?
        .into_iter()
        .find(|member| member.id == member_id)
        .context("Fleet transport member is not in the captain inventory")?;
    let stream = select_transport(&member.host(), route)?;
    proxy_stdio(stream)
}

fn select_transport(host: &str, route: TransportRoute) -> Result<TcpStream> {
    match route {
        TransportRoute::Auto | TransportRoute::Lan => TcpStream::connect((host, 22))
            .with_context(|| format!("connect to {host} on SSH port 22")),
        TransportRoute::Tailscale => {
            anyhow::bail!("no Tailscale peer mapping is recorded for this member; try `--via lan`")
        }
    }
}

fn proxy_stdio(mut stream: TcpStream) -> Result<()> {
    let mut upload = stream.try_clone().context("clone SSH transport socket")?;
    let _upload_thread = std::thread::spawn(move || -> io::Result<()> {
        io::copy(&mut io::stdin(), &mut upload)?;
        upload.shutdown(Shutdown::Write)
    });

    io::copy(&mut stream, &mut io::stdout()).context("read SSH transport")?;
    Ok(())
}

fn safe_proxy_executable(path: &Path) -> Result<&str> {
    let value = path
        .to_str()
        .context("Fleet executable path is not valid UTF-8")?;
    if !path.is_absolute()
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"/._-".contains(&byte))
    {
        anyhow::bail!(
            "Fleet executable path cannot be represented safely in OpenSSH ProxyCommand: {}",
            path.display()
        );
    }
    Ok(value)
}

fn quote_path(path: &Path) -> String {
    format!("\"{}\"", path.display().to_string().replace('"', "\\\""))
}

#[cfg(unix)]
fn set_mode(path: &Path, mode: u32) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
        .with_context(|| format!("set permissions on {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::Color;
    use crate::state::{LocalConfig, Machine, Role, STATE_VERSION};
    use uuid::Uuid;

    #[test]
    fn generated_config_uses_plain_local_host() {
        let temp = tempfile::tempdir().unwrap();
        let paths = StatePaths {
            root: temp.path().join(".fleet"),
        };
        let machine = Machine {
            id: Uuid::new_v4(),
            name: "obsidian".into(),
            color: Color::Violet,
            ssh_user: "dev".into(),
            os: "linux".into(),
            arch: "aarch64".into(),
            tools: vec![],
            public_identity: "ssh-ed25519 AAAA".into(),
            ssh_host_key: None,
        };
        paths
            .save(&LocalConfig {
                version: STATE_VERSION,
                role: Role::Captain,
                machine: machine.clone(),
                captain: None,
            })
            .unwrap();
        let mut member = machine;
        member.id = Uuid::new_v4();
        member.name = "emerald".into();
        member.ssh_host_key = Some("ssh-ed25519 AAAAHOST".into());
        skill::save_member(&paths, &member).unwrap();
        regenerate_with_executable(&paths, Path::new("/usr/local/bin/fleet")).unwrap();
        let generated = fs::read_to_string(paths.root.join("ssh_config")).unwrap();
        let known_hosts = fs::read_to_string(paths.known_hosts()).unwrap();
        assert!(generated.contains("Host emerald.local"));
        assert!(generated.contains("User dev"));
        assert!(generated.contains("StrictHostKeyChecking yes"));
        assert!(generated.contains("UpdateHostKeys no"));
        assert!(generated.contains("Port 22"));
        assert!(generated.contains(&format!(
            "ProxyCommand /usr/local/bin/fleet transport connect --member {}",
            member.id
        )));
        assert!(known_hosts.contains("emerald.local ssh-ed25519 AAAAHOST"));

        skill::remove_member(&paths, member.id).unwrap();
        regenerate_with_executable(&paths, Path::new("/usr/local/bin/fleet")).unwrap();
        assert!(
            !fs::read_to_string(paths.known_hosts())
                .unwrap()
                .contains("emerald.local")
        );
    }

    #[test]
    fn uninstall_filter_preserves_unrelated_ssh_configuration() {
        let existing = "Host github.com\n  User git\n# Fleet member configuration\nInclude \"/home/dev/.fleet/ssh_config\"\nHost example.com\n  User dev\n";
        let next =
            without_fleet_include(existing, "Include \"/home/dev/.fleet/ssh_config\"").unwrap();
        assert!(next.contains("Host github.com"));
        assert!(next.contains("Host example.com"));
        assert!(!next.contains("Fleet member configuration"));
        assert!(!next.contains(".fleet/ssh_config"));
    }

    #[test]
    fn fleet_include_is_rendered_before_existing_host_rules() {
        let existing = "Host *\n  StrictHostKeyChecking no\n";
        let include = "Include \"/home/dev/.fleet/ssh_config\"";
        let rendered = with_fleet_include(existing, include);
        assert!(rendered.find(include).unwrap() < rendered.find("Host *").unwrap());
    }

    #[test]
    fn proxy_executable_rejects_shell_metacharacters() {
        assert!(safe_proxy_executable(Path::new("/home/dev/.local/bin/fleet")).is_ok());
        for unsafe_path in ["relative/fleet", "/tmp/fleet build", "/tmp/fleet;other"] {
            assert!(safe_proxy_executable(Path::new(unsafe_path)).is_err());
        }
    }
}
