use crate::skill;
use crate::state::{StatePaths, atomic_write};
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

pub fn initialize(paths: &StatePaths) -> Result<()> {
    let home = dirs::home_dir().context("could not determine home directory")?;
    let ssh = home.join(".ssh");
    fs::create_dir_all(&ssh).context("create captain .ssh directory")?;
    set_mode(&ssh, 0o700)?;
    let config = ssh.join("config");
    let include = format!("Include {}", quote_path(&paths.root.join("ssh_config")));
    let existing = fs::read_to_string(&config).unwrap_or_default();
    if !existing.lines().any(|line| line.trim() == include) {
        let next = with_fleet_include(&existing, &include);
        atomic_write(&config, next.as_bytes(), 0o600)?;
    }
    regenerate(paths)
}

fn with_fleet_include(existing: &str, include: &str) -> String {
    let mut next = format!("# Fleet member configuration\n{include}\n");
    if !existing.is_empty() {
        next.push('\n');
        next.push_str(existing);
        if !next.ends_with('\n') {
            next.push('\n');
        }
    }
    next
}

pub fn uninstall(paths: &StatePaths) -> Result<()> {
    let home = dirs::home_dir().context("could not determine home directory")?;
    let config = home.join(".ssh/config");
    if config.exists() {
        let include = format!("Include {}", quote_path(&paths.root.join("ssh_config")));
        let existing = fs::read_to_string(&config).context("read SSH client config")?;
        if let Some(next) = without_fleet_include(&existing, &include) {
            atomic_write(&config, next.as_bytes(), 0o600)?;
        }
    }
    for managed in [paths.root.join("ssh_config"), paths.known_hosts()] {
        if managed.exists() {
            fs::remove_file(&managed).with_context(|| format!("remove {}", managed.display()))?;
        }
    }
    Ok(())
}

fn without_fleet_include(existing: &str, include: &str) -> Option<String> {
    let mut retained = Vec::new();
    let mut removed = false;
    for line in existing.lines() {
        if line.trim() == include {
            if retained
                .last()
                .is_some_and(|previous: &&str| previous.trim() == "# Fleet member configuration")
            {
                retained.pop();
            }
            removed = true;
            continue;
        }
        retained.push(line);
    }
    removed.then(|| {
        let mut next = retained.join("\n");
        if !next.is_empty() {
            next.push('\n');
        }
        next
    })
}

pub fn regenerate(paths: &StatePaths) -> Result<()> {
    let mut output = String::from("# Generated by Fleet. Do not edit.\n");
    let mut known_hosts = String::from("# Generated by Fleet. Do not edit.\n");
    for member in skill::load_members(paths)? {
        output.push_str(&format!(
            "\nHost {}\n  User {}\n  IdentityFile {}\n  IdentitiesOnly yes\n  UserKnownHostsFile {}\n  StrictHostKeyChecking yes\n",
            member.host(),
            member.ssh_user,
            quote_path(&paths.identity_dir().join("id_ed25519")),
            quote_path(&paths.known_hosts()),
        ));
        if let Some(host_key) = &member.ssh_host_key {
            let mut fields = host_key.split_whitespace();
            if let (Some(algorithm), Some(encoded)) = (fields.next(), fields.next()) {
                known_hosts.push_str(&format!("{} {} {}\n", member.host(), algorithm, encoded));
            }
        }
    }
    atomic_write(&paths.root.join("ssh_config"), output.as_bytes(), 0o600)?;
    atomic_write(&paths.known_hosts(), known_hosts.as_bytes(), 0o600)
}

fn quote_path(path: &Path) -> String {
    format!("\"{}\"", path.display().to_string().replace('"', "\\\""))
}

#[cfg(unix)]
fn set_mode(path: &Path, mode: u32) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
        .with_context(|| format!("set permissions on {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::Color;
    use crate::state::{LocalConfig, Machine, Role, STATE_VERSION};
    use uuid::Uuid;

    #[test]
    fn generated_config_uses_plain_local_host() {
        let temp = tempfile::tempdir().unwrap();
        let paths = StatePaths {
            root: temp.path().join(".fleet"),
        };
        let machine = Machine {
            id: Uuid::new_v4(),
            name: "obsidian".into(),
            color: Color::Violet,
            ssh_user: "dev".into(),
            os: "linux".into(),
            arch: "aarch64".into(),
            tools: vec![],
            public_identity: "ssh-ed25519 AAAA".into(),
            ssh_host_key: None,
        };
        paths
            .save(&LocalConfig {
                version: STATE_VERSION,
                role: Role::Captain,
                machine: machine.clone(),
                captain: None,
            })
            .unwrap();
        let mut member = machine;
        member.id = Uuid::new_v4();
        member.name = "emerald".into();
        member.ssh_host_key = Some("ssh-ed25519 AAAAHOST".into());
        skill::save_member(&paths, &member).unwrap();
        regenerate(&paths).unwrap();
        let generated = fs::read_to_string(paths.root.join("ssh_config")).unwrap();
        let known_hosts = fs::read_to_string(paths.known_hosts()).unwrap();
        assert!(generated.contains("Host emerald.local"));
        assert!(generated.contains("User dev"));
        assert!(generated.contains("StrictHostKeyChecking yes"));
        assert!(known_hosts.contains("emerald.local ssh-ed25519 AAAAHOST"));

        skill::remove_member(&paths, member.id).unwrap();
        regenerate(&paths).unwrap();
        assert!(
            !fs::read_to_string(paths.known_hosts())
                .unwrap()
                .contains("emerald.local")
        );
    }

    #[test]
    fn uninstall_filter_preserves_unrelated_ssh_configuration() {
        let existing = "Host github.com\n  User git\n# Fleet member configuration\nInclude \"/home/dev/.fleet/ssh_config\"\nHost example.com\n  User dev\n";
        let next =
            without_fleet_include(existing, "Include \"/home/dev/.fleet/ssh_config\"").unwrap();
        assert!(next.contains("Host github.com"));
        assert!(next.contains("Host example.com"));
        assert!(!next.contains("Fleet member configuration"));
        assert!(!next.contains(".fleet/ssh_config"));
    }

    #[test]
    fn fleet_include_is_rendered_before_existing_host_rules() {
        let existing = "Host *\n  StrictHostKeyChecking no\n";
        let include = "Include \"/home/dev/.fleet/ssh_config\"";
        let rendered = with_fleet_include(existing, include);
        assert!(rendered.find(include).unwrap() < rendered.find("Host *").unwrap());
    }
}
