use crate::cli::TransportRoute;
use crate::skill;
use crate::state::{StatePaths, atomic_write};
use anyhow::{Context, Result, bail};
use serde::Deserialize;
use std::fs;
use std::io;
use std::net::{Shutdown, SocketAddr, TcpStream, ToSocketAddrs};
use std::path::Path;
use std::sync::mpsc;
use std::time::Duration;
use uuid::Uuid;

pub fn initialize(paths: &StatePaths) -> Result<()> {
    let home = dirs::home_dir().context("could not determine home directory")?;
    let ssh = home.join(".ssh");
    fs::create_dir_all(&ssh).context("create captain .ssh directory")?;
    set_mode(&ssh, 0o700)?;
    let config = ssh.join("config");
    let include = format!("Include {}", quote_path(&paths.root.join("ssh_config")));
    let existing = fs::read_to_string(&config).unwrap_or_default();
    if !existing.lines().any(|line| line.trim() == include) {
        let next = with_fleet_include(&existing, &include);
        atomic_write(&config, next.as_bytes(), 0o600)?;
    }
    regenerate(paths)
}

fn with_fleet_include(existing: &str, include: &str) -> String {
    let mut next = format!("# Fleet member configuration\n{include}\n");
    if !existing.is_empty() {
        next.push('\n');
        next.push_str(existing);
        if !next.ends_with('\n') {
            next.push('\n');
        }
    }
    next
}

pub fn uninstall(paths: &StatePaths) -> Result<()> {
    let home = dirs::home_dir().context("could not determine home directory")?;
    let config = home.join(".ssh/config");
    if config.exists() {
        let include = format!("Include {}", quote_path(&paths.root.join("ssh_config")));
        let existing = fs::read_to_string(&config).context("read SSH client config")?;
        if let Some(next) = without_fleet_include(&existing, &include) {
            atomic_write(&config, next.as_bytes(), 0o600)?;
        }
    }
    for managed in [paths.root.join("ssh_config"), paths.known_hosts()] {
        if managed.exists() {
            fs::remove_file(&managed).with_context(|| format!("remove {}", managed.display()))?;
        }
    }
    Ok(())
}

fn without_fleet_include(existing: &str, include: &str) -> Option<String> {
    let mut retained = Vec::new();
    let mut removed = false;
    for line in existing.lines() {
        if line.trim() == include {
            if retained
                .last()
                .is_some_and(|previous: &&str| previous.trim() == "# Fleet member configuration")
            {
                retained.pop();
            }
            removed = true;
            continue;
        }
        retained.push(line);
    }
    removed.then(|| {
        let mut next = retained.join("\n");
        if !next.is_empty() {
            next.push('\n');
        }
        next
    })
}

pub fn regenerate(paths: &StatePaths) -> Result<()> {
    let executable = std::env::current_exe().context("locate the Fleet executable")?;
    regenerate_with_executable(paths, &executable)
}

fn regenerate_with_executable(paths: &StatePaths, executable: &Path) -> Result<()> {
    let executable = executable
        .to_str()
        .context("Fleet executable path is not valid UTF-8")?;
    if !Path::new(executable).is_absolute() {
        bail!("Fleet executable path must be absolute: {executable}");
    }
    let mut output = String::from("# Generated by Fleet. Do not edit.\n");
    let mut known_hosts = String::from("# Generated by Fleet. Do not edit.\n");
    for member in skill::load_members(paths)? {
        output.push_str(&format!(
            "\nHost {}\n  User {}\n  Port 22\n  IdentityFile {}\n  IdentitiesOnly yes\n  UserKnownHostsFile {}\n  StrictHostKeyChecking yes\n  UpdateHostKeys no\n  ProxyCommand {}\n",
            member.host(),
            member.ssh_user,
            quote_path(&paths.identity_dir().join("id_ed25519")),
            quote_path(&paths.known_hosts()),
            proxy_command(Path::new(executable), member.id, TransportRoute::Auto)?,
        ));
        if let Some(host_key) = &member.ssh_host_key {
            let mut fields = host_key.split_whitespace();
            if let (Some(algorithm), Some(encoded)) = (fields.next(), fields.next()) {
                known_hosts.push_str(&format!("{} {} {}\n", member.host(), algorithm, encoded));
            }
        }
    }
    atomic_write(&paths.root.join("ssh_config"), output.as_bytes(), 0o600)?;
    atomic_write(&paths.known_hosts(), known_hosts.as_bytes(), 0o600)
}

/// Implements the byte-stream side of Fleet's OpenSSH ProxyCommand.
///
/// The UUID is resolved only through the protected captain inventory. The
/// helper owns socket selection while OpenSSH retains hostname, host-key, and
/// user-authentication responsibility.
pub fn transport_connect(paths: &StatePaths, member_id: Uuid, route: TransportRoute) -> Result<()> {
    let member = skill::load_members(paths)?
        .into_iter()
        .find(|member| member.id == member_id)
        .context("Fleet transport member is not in the captain inventory")?;
    let stream = select_transport(paths, member_id, &member.host(), route)?;
    proxy_stdio(stream)
}

pub fn probe_transport(paths: &StatePaths, member_id: Uuid, route: TransportRoute) -> Result<()> {
    let member = skill::load_members(paths)?
        .into_iter()
        .find(|member| member.id == member_id)
        .context("Fleet transport member is not in the captain inventory")?;
    let _stream = select_transport_with_timeout(
        paths,
        member_id,
        &member.host(),
        route,
        Duration::from_millis(700),
    )?;
    Ok(())
}

#[derive(Debug, Deserialize)]
struct NetworkHintResponse {
    version: u32,
    #[serde(rename = "machineId")]
    machine_id: Uuid,
    #[serde(default)]
    tailscale: Option<NetworkHintTailscale>,
}

#[derive(Debug, Deserialize)]
struct NetworkHintTailscale {
    #[serde(rename = "dnsName")]
    dns_name: String,
}

/// Pull a member's local Tailscale identity over the already pinned SSH path.
/// A mapping is saved only after the captain's own Tailscale client resolves it
/// to a valid Tailscale address.
pub fn refresh_mapping(paths: &StatePaths, member: &crate::state::Machine) -> Result<bool> {
    let output = crate::remote::ssh_output_direct(
        &member.host(),
        "fleet network-hint --json",
        Duration::from_secs(8),
    )?;
    if !output.status.success() {
        anyhow::bail!("member network hint exited with {}", output.status);
    }
    if output.stdout.len() > 64 * 1024 {
        bail!("member network hint exceeded the 64 KiB output limit");
    }
    let hint: NetworkHintResponse =
        serde_json::from_slice(&output.stdout).context("decode member network hint")?;
    if hint.version != 1 || hint.machine_id != member.id {
        bail!("member network hint has an unsupported or mismatched identity");
    }
    let Some(tailscale) = hint.tailscale else {
        // A missing hint is not an authoritative deletion. The member may be
        // temporarily logged out or its daemon may be restarting; retain the
        // last-known mapping and let the selector fail over to LAN.
        return Ok(false);
    };
    let fqdn = crate::tailscale::normalize_fqdn(&tailscale.dns_name)?;
    crate::tailscale::peer_ips(&fqdn)
        .with_context(|| format!("resolve member Tailscale peer {fqdn}"))?;
    if !skill::load_members(paths)?
        .iter()
        .any(|candidate| candidate.id == member.id)
    {
        return Ok(false);
    }
    crate::tailscale::save_mapping(paths, member.id, &fqdn)?;
    Ok(true)
}

fn select_transport(
    paths: &StatePaths,
    member_id: Uuid,
    host: &str,
    route: TransportRoute,
) -> Result<TcpStream> {
    select_transport_with_timeout(paths, member_id, host, route, Duration::from_secs(7))
}

fn select_transport_with_timeout(
    paths: &StatePaths,
    member_id: Uuid,
    host: &str,
    route: TransportRoute,
    timeout: Duration,
) -> Result<TcpStream> {
    match route {
        TransportRoute::Lan => connect_lan(host, timeout),
        TransportRoute::Tailscale => connect_tailscale(paths, member_id, timeout),
        TransportRoute::Auto => {
            // A mapping is learned over the pinned LAN path after joining. Do
            // not spend time probing an unavailable Tailnet for older fleets
            // that predate this metadata; they retain the original LAN path.
            let mapped = match crate::tailscale::mapped_peer(paths, member_id) {
                Ok(mapped) => mapped,
                Err(error) => {
                    eprintln!("Fleet Tailscale mapping unavailable: {error:#}; using LAN");
                    None
                }
            };
            if mapped.is_none() {
                return connect_lan(host, timeout);
            }
            connect_auto(paths, member_id, host, timeout)
        }
    }
}

fn connect_lan(host: &str, timeout: Duration) -> Result<TcpStream> {
    let host = host.to_owned();
    let started = std::time::Instant::now();
    let (sender, receiver) = mpsc::channel();
    let resolver_host = host.clone();
    let error_host = host.clone();
    std::thread::spawn(move || {
        let result = (resolver_host.as_str(), 22)
            .to_socket_addrs()
            .map(|addresses| addresses.collect::<Vec<_>>())
            .map_err(|error| anyhow::anyhow!("resolve {error_host}: {error}"));
        let _ = sender.send(result);
    });
    let addresses = receiver
        .recv_timeout(timeout)
        .map_err(|_| anyhow::anyhow!("resolve {host} timed out"))??;
    connect_addresses(addresses, timeout.saturating_sub(started.elapsed()))
        .with_context(|| format!("connect to {host} on SSH port 22"))
}

fn connect_auto(
    paths: &StatePaths,
    member_id: Uuid,
    host: &str,
    timeout: Duration,
) -> Result<TcpStream> {
    let started = std::time::Instant::now();
    let (sender, receiver) = mpsc::channel();
    let lan_host = host.to_owned();
    let lan_sender = sender.clone();
    std::thread::spawn(move || {
        let result = connect_lan(&lan_host, timeout).map_err(|error| format!("{error:#}"));
        let _ = lan_sender.send(("LAN", result));
    });

    let mut errors = Vec::new();
    let head_start = timeout.min(Duration::from_millis(150));
    if let Ok((route, result)) = receiver.recv_timeout(head_start) {
        match result {
            Ok(stream) => return Ok(stream),
            Err(error) => errors.push(format!("{route}: {error}")),
        }
    }

    let tail_paths = paths.clone();
    let tail_sender = sender.clone();
    std::thread::spawn(move || {
        let result = connect_tailscale(&tail_paths, member_id, timeout)
            .map_err(|error| format!("{error:#}"));
        let _ = tail_sender.send(("Tailscale", result));
    });
    drop(sender);

    let deadline = started + timeout;
    while std::time::Instant::now() < deadline {
        let remaining = deadline.saturating_duration_since(std::time::Instant::now());
        match receiver.recv_timeout(remaining) {
            Ok((_route, Ok(stream))) => return Ok(stream),
            Ok((route, Err(error))) => errors.push(format!("{route}: {error}")),
            Err(_) => break,
        }
        if errors.len() >= 2 {
            break;
        }
    }
    bail!("no route connected: {}", errors.join("; "))
}

fn connect_tailscale(paths: &StatePaths, member_id: Uuid, timeout: Duration) -> Result<TcpStream> {
    let fqdn = crate::tailscale::mapped_peer(paths, member_id)?
        .context("no Tailscale peer mapping is recorded for this member; try `--via lan`")?;
    let addresses = crate::tailscale::peer_ips(&fqdn)?
        .into_iter()
        .map(|ip| SocketAddr::new(ip, 22))
        .collect::<Vec<_>>();
    connect_addresses(addresses, timeout)
        .with_context(|| format!("connect to Tailscale peer {fqdn} on SSH port 22"))
}

fn connect_addresses(addresses: Vec<SocketAddr>, timeout: Duration) -> Result<TcpStream> {
    if addresses.is_empty() {
        bail!("no route connected: no addresses were resolved");
    }
    let started = std::time::Instant::now();
    let (sender, receiver) = mpsc::channel();
    let total = addresses.len();
    for address in addresses {
        let sender = sender.clone();
        std::thread::spawn(move || {
            let result = TcpStream::connect_timeout(&address, timeout)
                .map_err(|error| format!("{address}: {error}"));
            let _ = sender.send(result);
        });
    }
    drop(sender);
    let mut errors = Vec::new();
    for _ in 0..total {
        let remaining = timeout.saturating_sub(started.elapsed());
        if remaining.is_zero() {
            break;
        }
        match receiver.recv_timeout(remaining) {
            Ok(Ok(stream)) => return Ok(stream),
            Ok(Err(error)) => errors.push(error),
            Err(_) => break,
        }
    }
    anyhow::bail!(
        "no route connected{}",
        if errors.is_empty() {
            String::new()
        } else {
            format!(": {}", errors.join("; "))
        }
    )
}

fn proxy_stdio(mut stream: TcpStream) -> Result<()> {
    let mut upload = stream.try_clone().context("clone SSH transport socket")?;
    let _upload_thread = std::thread::spawn(move || -> io::Result<()> {
        io::copy(&mut io::stdin(), &mut upload)?;
        upload.shutdown(Shutdown::Write)
    });

    io::copy(&mut stream, &mut io::stdout()).context("read SSH transport")?;
    Ok(())
}

fn safe_proxy_executable(path: &Path) -> Result<&str> {
    let value = path
        .to_str()
        .context("Fleet executable path is not valid UTF-8")?;
    if !path.is_absolute() || value.bytes().any(|byte| byte == b'\r' || byte == b'\n') {
        anyhow::bail!(
            "Fleet executable path cannot be represented safely: {}",
            path.display()
        );
    }
    Ok(value)
}

/// Render the shell command OpenSSH runs for a ProxyCommand. OpenSSH invokes
/// this value through the user's shell, so the executable is single-quoted
/// even when its installation path contains spaces or shell metacharacters.
pub(crate) fn proxy_command(
    executable: &Path,
    member_id: Uuid,
    route: TransportRoute,
) -> Result<String> {
    let executable = safe_proxy_executable(executable)?;
    Ok(format!(
        "{} transport connect --member {} --via {}",
        shell_quote(executable),
        member_id,
        route
    ))
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('%', "%%").replace('\'', "'\\''"))
}

fn quote_path(path: &Path) -> String {
    format!("\"{}\"", path.display().to_string().replace('"', "\\\""))
}

#[cfg(unix)]
fn set_mode(path: &Path, mode: u32) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
        .with_context(|| format!("set permissions on {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::Color;
    use crate::state::{LocalConfig, Machine, Role, STATE_VERSION};
    use uuid::Uuid;

    #[test]
    fn generated_config_uses_plain_local_host() {
        let temp = tempfile::tempdir().unwrap();
        let paths = StatePaths {
            root: temp.path().join(".fleet"),
        };
        let machine = Machine {
            id: Uuid::new_v4(),
            name: "obsidian".into(),
            color: Color::Violet,
            ssh_user: "dev".into(),
            os: "linux".into(),
            arch: "aarch64".into(),
            tools: vec![],
            public_identity: "ssh-ed25519 AAAA".into(),
            ssh_host_key: None,
        };
        paths
            .save(&LocalConfig {
                version: STATE_VERSION,
                role: Role::Captain,
                machine: machine.clone(),
                captain: None,
            })
            .unwrap();
        let mut member = machine;
        member.id = Uuid::new_v4();
        member.name = "emerald".into();
        member.ssh_host_key = Some("ssh-ed25519 AAAAHOST".into());
        skill::save_member(&paths, &member).unwrap();
        regenerate_with_executable(&paths, Path::new("/usr/local/bin/fleet")).unwrap();
        let generated = fs::read_to_string(paths.root.join("ssh_config")).unwrap();
        let known_hosts = fs::read_to_string(paths.known_hosts()).unwrap();
        assert!(generated.contains("Host emerald.local"));
        assert!(generated.contains("User dev"));
        assert!(generated.contains("StrictHostKeyChecking yes"));
        assert!(generated.contains("UpdateHostKeys no"));
        assert!(generated.contains("Port 22"));
        assert!(generated.contains(&format!(
            "ProxyCommand '/usr/local/bin/fleet' transport connect --member {} --via auto",
            member.id
        )));
        assert!(known_hosts.contains("emerald.local ssh-ed25519 AAAAHOST"));

        skill::remove_member(&paths, member.id).unwrap();
        regenerate_with_executable(&paths, Path::new("/usr/local/bin/fleet")).unwrap();
        assert!(
            !fs::read_to_string(paths.known_hosts())
                .unwrap()
                .contains("emerald.local")
        );
    }

    #[test]
    fn uninstall_filter_preserves_unrelated_ssh_configuration() {
        let existing = "Host github.com\n  User git\n# Fleet member configuration\nInclude \"/home/dev/.fleet/ssh_config\"\nHost example.com\n  User dev\n";
        let next =
            without_fleet_include(existing, "Include \"/home/dev/.fleet/ssh_config\"").unwrap();
        assert!(next.contains("Host github.com"));
        assert!(next.contains("Host example.com"));
        assert!(!next.contains("Fleet member configuration"));
        assert!(!next.contains(".fleet/ssh_config"));
    }

    #[test]
    fn fleet_include_is_rendered_before_existing_host_rules() {
        let existing = "Host *\n  StrictHostKeyChecking no\n";
        let include = "Include \"/home/dev/.fleet/ssh_config\"";
        let rendered = with_fleet_include(existing, include);
        assert!(rendered.find(include).unwrap() < rendered.find("Host *").unwrap());
    }

    #[test]
    fn proxy_executable_accepts_shell_metacharacters_with_quoting() {
        assert!(safe_proxy_executable(Path::new("/home/dev/.local/bin/fleet")).is_ok());
        assert!(safe_proxy_executable(Path::new("/tmp/fleet build")).is_ok());
        assert_eq!(
            shell_quote("/tmp/fleet build;echo 'oops'"),
            "'/tmp/fleet build;echo '\\''oops'\\'''"
        );
        assert!(safe_proxy_executable(Path::new("/tmp/fleet\nHost *")).is_err());
        assert!(safe_proxy_executable(Path::new("relative/fleet")).is_err());
    }

    #[test]
    fn network_hint_requires_the_member_identity_and_camel_case_fields() {
        let id = Uuid::new_v4();
        let hint: NetworkHintResponse = serde_json::from_value(serde_json::json!({
            "version": 1,
            "machineId": id,
            "tailscale": { "dnsName": "emerald.example.ts.net" }
        }))
        .unwrap();
        assert_eq!(hint.version, 1);
        assert_eq!(hint.machine_id, id);
        assert_eq!(hint.tailscale.unwrap().dns_name, "emerald.example.ts.net");
    }
}
